import { Router } from "express";
import animes from "./animes";
import episodes from "./episodes";
import openings from "./openings";
import endings from "./endings";
import filters from "./filters";
import media from "./media";
import seasions from './seasions';
//import telegram from './telegram';
import token from "./token";
const router = Router();
router.use("/animes", animes);
router.use('/filters', filters);
router.use('/media', media);
router.use("/episodes", episodes);
router.use("/openings", openings);
router.use("/endings", endings);
router.use('/seasions', seasions);
router.use('/token',token);
//router.use('/telegram',telegram);
export default router;