import express from 'express';
import cors from "cors";
import DBConnect from "./db/index";
import apitoken from "./middlewares/apitoken";
import notfound from "./middlewares/404";
import errors from "./middlewares/error";
import routes from "./routes/api/index";
import statics from "./routes/static/index";
DBConnect();
const app = express();
app.use(cors());
app.use(express.text({ type: "text/html" }));
app.use(express.json({ type: "application/json" }));
app.use(express.urlencoded({ extended: true }));
app.use(apitoken);
app.use("/api", routes);
app.use(statics);
app.use(errors);
app.use(notfound);
export default app;